import Head from 'next/head'
import Header from "../components/Header"
import Navbar from "../components/Navbar"
import Results from "../components/Results"
import requests from "../utility/requests"

export default function Home({ results }) {
  return (
    <div>
      <Head>
        <title>Hulu Streaming Service</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Navbar />
      <Results results={results}/>

    </div>
  )
}

// Server-side rendering -> The first thing to render on the website even before the Actual page components
// Here After fetching the data from API, We'll use that as a props

export async function getServerSideProps(context) {
  const genre = context.query.genre;

  const request = await fetch(
    `https://api.themoviedb.org/3${requests[genre]?.url || requests.fetchTrending.url
  }`
  ).then(res => res.json());

  return {
    props: {
      results: request.results,
    },
  }
}